### PR TITLE
Use qualification API

### PR DESCRIPTION
**Pull request by acampbel**
Here is an interesting possible improvement. may provide better diagnostics on failure.

### CODE REVIEW

**Comment by acampbel** [comment]
Failure is unrelated to code changed in PR. Couldn't debug this failure locally because the tests fail due to not finding the function or variable 'chop'?

**Comment by wspr** [comment]
@acampbel — (just quickly, home with sick kid) — I did have a false negative at some point with this test suite and re-running the travis build fixed it up. Not sure what caused it, perhaps I have a test using some random numbers that has some edge cases.

I haven't used chop.m in years and years (evidently); it can be found here:

    /Applications/MATLAB_R2018a.app/toolbox/control/ctrlobsolete/chop.m

I happily see that Matlab now (since 2014) has a round function that accepts a second argument for precision, so that's an easy fix for me.

**Comment by acampbel** [comment]
Ah I see. The matlab I was running locally didn’t have the control toolbox. not sure about the failure but randomness could have been the culprit for sure.

I hope your child gets better

**Comment by wspr** [comment]
Thanks very much! I can see the power of this type of testing. It took me a few minutes to figure out the magic of automatic iteration over the variables in the `properties` :)

**Pull request merged**
